title: Akash Rodhiya # your name (or website title) here
logo: "/images/photo3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Doctoral Candidate, 
  <br>
  Tandon School of Engineering,
  <br>
  New York University (2023-present)
  <br><br>
  Senior Research Fellow,
  <br>
  Department of Physics,
  <br>
  Indian Institute of Technology Kanpur (2022-2023)
  <br><br>
  M-tech (Research), CDS, 
  <br>
  Indian Institute of Science Bangalore (2019-2022)
  <br><br>
  Bachelor of Technology in Mechanical Engineering,
  <br>
  Indian Institute of Technology (BHU) Varanasi (2015-2019)
  
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
